### ISSUE TITLE
Error when preparing data with parallelCluster feature

### ISSUE THREAD

**Issue by guangyuan** [WinVector/vtreat#11]
My code:

`		parallelCluster <- parallel::makeCluster(ncores)
	 	in_data$bst_pred <- predict(bst_xgb, as.matrix(prepare(treatmentsZ, in_data, parallelCluster = parallelCluster)))
	 	parallel::stopCluster(parallelCluster)
`

and I got error
> `Error in checkForRemoteErrors(val) : 
>   10 nodes produced errors; first error: could not find function ".cleanColumn"
> Calls: source ... clusterApplyLB -> dynamicClusterApply -> checkForRemoteErrors
> In addition: Warning message:
> In prepare(treatmentsZ_svsd, in_vh_data, parallelCluster = parallelCluster) :
>   treatments desined with vtreat version 0.5.32 and preparing data.frame with vtreat version 1.0.1
> Execution halted

Any idea how to fix this? Thanks in advance.

**Comment by JohnMount** [comment]
I'll try to take a look at that on my end.  Sorry that is causing a problem.

**Comment by JohnMount** [comment]
I re-tested here.  Things seem to work on the basic parallel cases.

One thing that could cause this is if `vtreat`'s install is not available to the parallel workers.  This can happen if they are different machines (and it isn't on those machines), or even a different user ID (and `vtreat` is installed as user package and not a system package), or even a different `R` binary (and what set of system packages are available is different).

Also can you please try it with the prepare outside of the `xgboost` predict method (just to see).  I would suggest seeing if your setup can run the following as test: https://github.com/WinVector/vtreat/blob/master/tests/testthat/testParallel.R .

Another one issue is the version of `vtreat` used to build the treatments is different than the one applying (always a concern).

**Comment by guangyuan** [comment]
@JohnMount Thanks for looking into this.

This was run on a Linux machine. I will go test preparing the data outside the `xgboost` predict function, and come back with updated results.

Thanks for providing such a great tool for data preparation!

**Comment by guangyuan** [comment]
@JohnMount 

@JohnMount  It did work well when the data was prepared outside the `xgboost` predict function. So I guess there's some implied  conflict between the parallel computing mechanism in `vtreat` and that in `xgboost`. Not sure how complicated it would be, but it will be nice to add a feature in the current package to detect if the function is called within, say, `xgboost` predict function, and switch automatically to disable the parallel computing and give a warning. Or I just have to change my coding habit to not put to many things in one line of code :)

**Comment by JohnMount** [comment]
Thanks for confirming that.  I'll add that to the help at some point.
