### ISSUE TITLE
Warning on new levels of factor variables

### ISSUE THREAD

**Issue by guangyuan** [WinVector/vtreat#13]
A nice feature to have for the `prepare`  function is that when a new level of a factor/character variable was read in, the function should be able to give a warning and an option to error out. In some cases, we probably don't intend to let the model to predict on some data that it never saw during the model training. I read the documentation, but didn't find how this is handled explicitly. But base on the usage, it seems the function just ignore the new level, and basically include it in the 'reference' level.

Thanks.

**Comment by JohnMount** [comment]
Actually the new levels can (in some cases) be pooled-in with a special rare level code.

However, either way your suggestion is a good one.  I'll add the warning as a user controllable option.

**Comment by JohnMount** [comment]
I have added some novel level tools (kept them a bit separate as they do require additional record keeping and overhead).  On the [parallel_ind](https://github.com/WinVector/vtreat/tree/parallel_ind) branch of `vtreat` you can now [ask for levels of a set of variables to be tracked with a new method: `track_values`.  If this tracking structure is added to prepare it will generate warnings.  Also there is a tool for finding the rows and columns that have novel levels: `novel_value_summary`.

This should be pushed out in the upcoming `1.0.3` version of `vtreat` after more testing.

Again thanks for your feedback and good idea.
