### ISSUE TITLE
Unable to create "rare" level for categorical variable if rareCount exceeds a latent threshold

### ISSUE THREAD

**Issue by peterzsohar** [WinVector/vtreat#19]
I am trying to create a "rare" level dummy from a two-level factor variable that has a rare level with low frequency.
In the test/holdout data I expect to see a potential third level (also rare) that I would like to bundle with the rare level in the train data after applying the treatment.

Example below:
```
library(vtreat)

set.seed(1133)
N = 10000
p0_y = 0.5
p0_x = 0.999

df = data.frame(y = sample(c(0, 1), size = N, prob = c(p0_y, 1 - p0_y), replace = TRUE),
                x = as.factor(sample(c(0, 1), size = N, prob = c(p0_x, 1 - p0_x), replace = TRUE)))

print(summary(df))

#       y          x       
# Min.   :0.0000   0:9987  
# 1st Qu.:0.0000   1:  13  
# Median :1.0000           
# Mean   :0.5034           
# 3rd Qu.:1.0000           
# Max.   :1.0000 

treatmentsC = designTreatmentsC(dframe = df,
                                varlist = c("x"),
                                outcomename = "y",
                                outcometarget = 1,
                                minFraction = 0.0,
                                rareCount = 50)

[1] "vtreat 1.2.1 inspecting inputs Tue Jul 03 19:02:23 2018"
[1] "designing treatments Tue Jul 03 19:02:23 2018"
[1] " have initial level statistics Tue Jul 03 19:02:23 2018"
Error in .designTreatmentsXS(dframe, varlist, outcomename, zoY, zC, zTarget,  : 
  no usable vars
```
I would expect the get back variables `x_lev_x_0` and `x_lev_rare`.
Then if the test/holdout data has factor level `2` it could be bundled with `x_lev_rare`.

However, if I set `rareCount = 0` (or anything less than the frequency of the rare level) I get `x_lev_x_0` and `x_lev_x_1` as expected but then I can't bundle the novel level from the test/holdout without manually inspecting `novel_level_summary()`.

**Comment by JohnMount** [comment]
I can't go through this in detail for a couple of days, but it sounds like you properly understand the design intent of rare coding and this is a case we want to get right.  I will work on reproducing the sequence and tell you what I see in a bit.

**Comment by peterzsohar** [comment]
@JohnMount This line implies the behavior that leads to the issue.

https://github.com/WinVector/vtreat/blob/ffa68871f7ec89909f7365e499d112dd5d73d1b8/R/vtreatImpl.R#L208

```
counts = c(100, 8, 2)
names(counts) = c("0", "1", "2")
totMass = sum(counts)

rareCount = 9
safeLevs = names(counts)[(counts>rareCount) & (counts<(totMass-rareCount))]
print(safeLevs)
# [1] "0"

rareCount = 10
safeLevs = names(counts)[(counts>rareCount) & (counts<(totMass-rareCount))]
print(safeLevs)
# character(0)
```

**Comment by JohnMount** [comment]
@peterzsohar Thank you so much for filing that and for your patient analysis.  You identified the bug, and your earlier suspicion that part of the bug was categorical with two levels is also correct.  I wrote bad code in level selector, and I have now removed that mistake.  Your example now looks like the following:

```r
library(vtreat)

set.seed(1133)
N = 10000
p0_y = 0.5
p0_x = 0.999

df = data.frame(y = sample(c(0, 1), size = N, prob = c(p0_y, 1 - p0_y), replace = TRUE),
                x = as.factor(sample(c(0, 1), size = N, prob = c(p0_x, 1 - p0_x), replace = TRUE)))

# print(summary(df))

treatmentsC = designTreatmentsC(dframe = df,
                                varlist = c("x"),
                                outcomename = "y",
                                outcometarget = 1,
                                minFraction = 0.0,
                                rareCount = 50,
                                rareSig = NULL)

treatmentsC

#      varName varMoves          rsq       sig needsSplit extraModelDegrees origName code
# 1 x_lev_rare     TRUE 4.622784e-06 0.8001548      FALSE                 0        x  lev
# 2  x_lev_x_0     TRUE 4.622784e-06 0.8001548      FALSE                 0        x  lev

d2 <- data.frame(x = c("0", "1", "2"))
prepare(treatmentsC, d2)
#   x_lev_rare x_lev_x_0
# 1          0         1
# 2          1         0
# 3          1         0
```

Commit 647cc00d8ad7d77bc9c8e07fc0b6ba4d85cf014c ( https://github.com/WinVector/vtreat/commit/647cc00d8ad7d77bc9c8e07fc0b6ba4d85cf014c ) fixes the issue.  I'll push this to CRAN as vtreat 1.2.2 soon. 

Thank you so much for working on this issue.  The treatment of rare and novel levels is supposed to be one of the fairly unique features of vtreat, and it is good to get it working at full capacity.
