### ISSUE TITLE
Variable Importance

### ISSUE THREAD

**Issue by drag05** [WinVector/vtreat#21]
Which would be the correct aggregation statistic for treated variable importance when aggregated by their old names (e.g. outputs from **caret::varImp()** or **randomForest::importance**)?

For example:
``` aggregate(list('oldVar_catB', 'oldVar_poolC', 'oldVar_lev'), by = grep('oldVar', …), FUN = ?, ...)```

**Comment by JohnMount** [comment]
My guess is max: as none of the derived variables exist unless the producing variable is present.  However likely there are exceptions.
