### ISSUE TITLE
vtreat 1.3.0

### ISSUE THREAD

**Issue by drag05** [WinVector/vtreat#22]
`mkCrossFrameMExperiment` output: 

Column names of y-dependent treatments in `cross_frame` data frame differ from those obtained with `prepare` function.

 `cross_frame` names start with the class label 

``` <class_label>.X<class_label>_varName```

while `prepare` gives

```  X<class_label>_varName ```

which are similar with the `score_frame` varNames

**Comment by JohnMount** [comment]
Argh, sorry about that.  I'll look into that right now.  Thanks for all of your input.

**Comment by JohnMount** [comment]
I think I have fixed it ([example](https://winvector.github.io/vtreat/articles/MultiClassVtreat.html)) in https://github.com/WinVector/vtreat/commit/3932d6fd58852681cafbb6e5d4216ffaef16ced7 .

**Comment by drag05** [comment]
Dr. Mount,

Thank you for taking the time to look into this issue! I understand this change
is implemented in v 1.3.1. 

On  a slightly different topic: I wonder if you would be so kind as to direct me
to detailed information on y-dependent treatments: have these variables similar
meaning to the factors in a DOE design matrix (setting aside their observational
character in this case)? 

Thank you,

Dragos Bandur

**Comment by JohnMount** [comment]
"y-aware" is just my colloquial name for variable treatments that use information from the dependent variable (or outcome or y-variable) and not related to design of experiments.  Examples  are the effects/impact codes from `vtreat` (the `catB`s and so on) and also the y-aware scaling from [here](http://www.win-vector.com/blog/2016/06/y-aware-scaling-in-context/).

**Comment by drag05** [comment]
Dr. Mount,

My question was a bit unclear: I was referring to the `y_dependent_treatments` argument of `mkCrossFrameMExperiment()` function call.

Thank you,
drag05

**Comment by drag05** [comment]
Dr. Mount, 

Prompt as always, thank you for that! I am running h2o on data prepared with
vtreat.
