### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by AtharKharal** [WinVector/vtreat#28]
In the example, the command 
unpack[
  transform = treatments,
  d_prepared = crossFrame
  ] <- vtreat::mkCrossFrameCExperiment( ………..)

produces error saying 'treatments' is missing. This may be rectified.

**Comment by JohnMount** [comment]
I would ask that you double check you have latest versions of vtreat (1.5.2) and wrapr (1.9.6).  The example appears to run correctly here https://github.com/WinVector/vtreat/blob/master/Examples/Classification/Classification.md .  If you can produced a reproducible failure (small code that triggers the error), please re-open this issue or even file other.
