### ISSUE TITLE
[New Feature]: Increase the possibilities of "designTreatmentsZ()".

### ISSUE THREAD

**Issue by coforfe** [WinVector/vtreat#3]
Hello John,

Thanks for the new `vtreat`version.
Perhaps I did not realize the existente of **designTreamentsZ()** function in the previous version. But now that I know it I see more possibilities that can enrich it to treat categorical variables in particular.

Now, for categorical variables (I am thinking more on variables with high-cardinality) I have already tested in same data competitions that using just the count of each category performs better than its frequencies, as it works now (I know this as *Hot Encoding*).

This also opens new possibilities in the way that you can also consider _interactions_ of variables. With two categorical variables you can paste each row and apply again the _hot-encoding_ to the resulting variable `designTreatmentsZ()` could include the possibility to define the kind of resulting output could be, if hot_encoding or frequencies, and also provide a set of variables to get the cross-interaction. Again, I have tested this approach with success in some data competitions.

I thought that these were the most interesting _feature engineering_ approaches until I read this yesterday: 

[https://www.linkedin.com/pulse/feature-engineering-data-scientists-secret-sauce-ashish-kumar](https://www.linkedin.com/pulse/feature-engineering-data-scientists-secret-sauce-ashish-kumar)

which opens new coding possbilities for categorical as well as numeric variables that would be very interesting to see implemented in *vtreat*. These are _featuring engineering_ transformation that as you can read in the post are in the day to day data scientist arsenal.

Thanks,
Carlos Ortega

**Comment by JohnMount** [comment]
Thanks Carlos,

A lot of the features mentioned in the Ashish Kumar article have been in vtreat for some time.  We have catP (prevalence or ratio features; really should encode same information as counts), catD (deviation features), catN (conditional expectations) and catB (sub-model probabilities).  For another transform (not in vtreat) see this on "signed pseudo-logs": http://www.win-vector.com/blog/2012/03/modeling-trick-the-signed-pseudo-logarithm/ .

Our primary thrust is y-aware methods, so definitely see if you can use one of `designTreatmentsC` or `designTreatmentsN` for your work.   A lot of this is covered in our vignettes: http://winvector.github.io/vtreat/

We do have lots of ideas for transforms- but we are trying to introduce them only after we have  good example where they are really necessary.  So I'll close the issue- and say stay tuned for more features as we introduce and document them.

John

**Comment by coforfe** [comment]
Thanks John for the indications.
I am going to go deeper in using all the possibilities `vtreat` currently offers.

Thanks again,
Carlos.
