### ISSUE TITLE
Question: Recommendation for Imbalanced Classification problem

### ISSUE THREAD

**Issue by sainathadapa** [WinVector/vtreat#5]
While working with imbalanced datasets, do you recommend that the input be processed (downsampling, upsampling, or SMOTE, etc), before using designTreatmentsC on it?

**Comment by JohnMount** [comment]
Hi Sainath Adapa,

Good question.

The design intent of vtreat is you should not have to resample for outcome imbalanced datasets as most of the re-encodings (such as impact coding) are roughly calculated in change in logit odds-ratio as a difference from base-prevelance (hoping to make the original target prevelance not factor in).

If you do want to adjust, my favorite adjustment is just to re-weight the rare class (either through up-sampling the rare class or using the weights control) to make both categorical outcomes have 50% of the weight.

Of course this is all independent of what you want to do for your next-stage machine learning.

John
