### ISSUE TITLE
Package site

### ISSUE THREAD

**Issue by sainathadapa** [WinVector/vtreat#6]
At this point, to understand the motivations, background information and usage of vtreat, requires going through a couple of papers, few blog posts, and vignettes. As such having a small website with all of these consolidated at a single source is a nice thing to have. And you can keep updating the site with the latest information regarding this package.

It is very easy to create a doc site for a package using github-pages. Not that you need it, since you guys have a full-fledged site at http://www.win-vector.com/site/.

**Comment by JohnMount** [comment]
A good suggestion, thank you.  We will probably make a doc site here on github-pages after I research how to do that.  I'll close this when we finish (probably end of March).

**Comment by JohnMount** [comment]
Started the site: [http://winvector.github.io/vtreat/](http://winvector.github.io/vtreat/).
