### ISSUE TITLE
More helpful error message in mkCrossFrameNExperiment

### ISSUE THREAD

**Issue by lawwu** [WinVector/vtreat#8]
It would be great if a more helpful error message were thrown when running mkCrossFrameNExperiment on a data frame where the outcome variable has NA values.

Right now the error message is:
`Error in if (min(ycol) >= max(ycol)) { : 
  missing value where TRUE/FALSE needed`

Something like:
`Error: There are missing values in the predictor column. Cannot run the experiment.`

I may do a pull request but just wanted to throw this out there.

**Comment by JohnMount** [comment]
That is a good critique, thank you. 

I have just added such a message to the main `vtreat` entry points.  The message s are variations of "`There are missing values in the outcome column, can not run mkCrossFrameNExperiment.`"  So it should be available now in the development version of `vtreat`.
